export const i18n = {
    fr: {
        copyrightNotice: "CV généré par mon propre moteur de matching vectoriel (Mistral & SQLite)",
        educationTitle: "Éducation",
        experienceTitle: "Expériences Professionnelles",
        projectTitle: "Projets & Réalisations",
        skillsTitle: "Compétences & Langues"
    },
    en: {
        copyrightNotice: "CV generated by my own vector matching engine (Mistral & SQLite)",
        educationTitle: "Education",
        experienceTitle: "Professional Experiences",
        projectTitle: "Projects & Achievements",
        skillsTitle: "Skills & Languages"
    }
}