name: macOS Debug Flow

on:
  push:
    branches:
      - fix/test-macOS

jobs:
  debug:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Find dependencies
        run: |
            find node_modules -name "libonnxruntime*" -print

            echo "=== TRANSFORMERS ==="
            npm ls @xenova/transformers

            echo "=== ONNX RUNTIME ==="
            npm ls onnxruntime-node

            echo "=== ONNX FILES ==="
            find node_modules -iname "*onnx*" -print

            echo "=== DYLIBS ==="
            find node_modules -name "*.dylib" -print

      - name: Run Forge Make
        run: npm run make
      - name: List Output
        run: |
            APP="out/cv-maker-darwin-arm64/cv-maker.app"

            echo "=== FINAL ONNX FILES ==="
            find "$APP" -iname "*onnx*" -print

            echo "=== FINAL DYLIBS ==="
            find "$APP" -name "*.dylib" -print

            echo "=== ASAR CONTENT ==="
            npx asar list "$APP/Contents/Resources/app.asar" | grep -i onnx || true

            echo "=== ASAR UNPACKED ==="
            find "$APP/Contents/Resources/app.asar.unpacked" -iname "*onnx*" -print

            find "$APP" -name "onnxruntime_binding.node" -print

            find "$APP" -path "*onnxruntime-node*" -print